title: Technical Project Manager
author: Varnasus
email: zvarney@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first stab at GitHub pages!

# social links
twitter_username: your-twitter-handle
github_username:  @Varnasus
theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
